### ISSUE TITLE
will be added support for iOS 17?

### ISSUE THREAD

**Issue by idanhauser** [JinjunHan/iOSDeviceSupport#19]

**Comment by JinjunHan** [comment]
it not contain in Xcode15, waiting a solution

**Comment by JinjunHan** [comment]
In the terminal run:
`defaults write com.apple.dt.Xcode DVTEnableCoreDevice enabled`
Then restart Xcode 14.3.1 the iOS 17 device will show up in Xcode like below and you can run and debug the app as usual. (You may need to go to Devices and Simulators to pair/trust the device)

**Comment by JinjunHan** [comment]
the solution from: https://developer.apple.com/forums/thread/730947
