### ISSUE TITLE
anyone have iOS17 support file?

### ISSUE THREAD

**Issue by lizhili42** [JinjunHan/iOSDeviceSupport#21]
please help, thx.

**Comment by JinjunHan** [comment]
Oh. I has download the Xcode15 Release, but can not found the iOS 17. 
Can you try this file? It make from 16.4, tell me the result, thx.
[17.0.zip](https://github.com/JinjunHan/iOSDeviceSupport/files/12655149/17.0.zip)

**Comment by JinjunHan** [comment]
In the terminal run:
`defaults write com.apple.dt.Xcode DVTEnableCoreDevice enabled`
Then restart Xcode 14 the iOS 17 device will show up in Xcode like below and you can run and debug the app as usual. (You may need to go to Devices and Simulators to pair/trust the device)

the solution from: https://developer.apple.com/forums/thread/730947
