### ISSUE TITLE
如何获取16.7的support文件。

### ISSUE THREAD

**Issue by nanski** [JinjunHan/iOSDeviceSupport#24]
如何获取16.7的support文件。

**Comment by JinjunHan** [comment]
试试这个？[16.7.zip](https://github.com/JinjunHan/iOSDeviceSupport/files/12836986/16.7.zip)

**Comment by kenanwangyi** [comment]
> 试试这个？[16.7.zip](https://github.com/JinjunHan/iOSDeviceSupport/files/12836986/16.7.zip)

大佬，没法下载啊

**Comment by JinjunHan** [comment]
> > 试试这个？[16.7.zip](https://github.com/JinjunHan/iOSDeviceSupport/files/12836986/16.7.zip)
> 
> 大佬，没法下载啊

[16.7.zip](https://github.com/JinjunHan/iOSDeviceSupport/files/12837075/16.7.zip)

**Comment by jfyGiveMeFive** [comment]
同求16.7，这个不能下载

**Comment by JinjunHan** [comment]
> 同求16.7，这个不能下载

你看上面那条？后面重新发的也不行吗

**Comment by jfyGiveMeFive** [comment]
> > 同求16.7，这个不能下载
> 
> 你看上面那条？后面重新发的也不行吗

挨个点了一下，可以了。多谢

**Comment by JinjunHan** [comment]
> > > 同求16.7，这个不能下载
> > 
> > 
> > 你看上面那条？后面重新发的也不行吗
> 
> 挨个点了一下，可以了。多谢

你试下行不行，可以的话，反馈给我，我更新上去
