### ISSUE TITLE
请问什么时候增加15.8版本的

### ISSUE THREAD

**Issue by henrybridge** [JinjunHan/iOSDeviceSupport#28]
或者给个思路刷机降级，现在的6s还能刷机降级吗，降级完会破坏什么东西吗，还是完全原生的

**Comment by JinjunHan** [comment]
15.8应该挺久了吧？正常Xcode 都行，你xcode 版本多少，看看里面最高是iOS多少。如果真不行，你把 15.7 复制一份重命名成 15.8 就可以
